name: Hello World
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello, World!"

    - uses: actions/checkout@v4
      with:
        repository: 'crap-test/Hello-World'

    - name: List files
      run: ls -la
        